### PR TITLE
[LOOM-1377]: transform to mjs & replace svg2react with svgr

### PR DESCRIPTION
**Pull request by mungodewar**
Task
- Transform to `mjs`
- Replace svg2react with svgr
- Created components are now `.jsx` not `.js`
- Created components how have `.d.ts` typings files

### CODE REVIEW

**Comment by xalechez** [comment]
Looks great! I guess the only thing missing is transpliation of tsx icons

**Comment by mungodewar** [comment]
> Looks great! I guess the only thing missing is transpliation of tsx icons

I was considering that this would be handled by bpk, as the dist get's `cp`'d into the repo. https://github.com/Skyscanner/backpack/blob/main/gulpfile.js/bpk-component-icon/gulpfile.babel.js

Not ideal, however, if/when we wanted to remove that weirdness we can tackle transpilation at that point. Or do you think that is a bit dangerous?

**Comment by xalechez** [comment]
I'd rather go safe and not publish tsx to npm, in case someone is using this library directly (which can always be the case with OSS)

**Comment by mungodewar** [comment]
> I'd rather go safe and not publish tsx to npm, in case someone is using this library directly (which can always be the case with OSS)

Yup, that's fair.

**Comment by metalix2** [comment]
I think it looks good though is it worth updating/adding to the readme the process that happens to generate these svg components and how to manage their transformation with the svgr build file? Just for the next person to know how all this works.

**Review by metalix2 — APPROVED** [review]
Love it!

**Pull request merged**
